apiVersion: batch/v1
kind: CronJob
metadata:
  name: go-weather-ingest
spec:
  schedule: "* /5 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: go-weather-api
            image: goApi
            imagePullPolicy: IfNotPresent
          restartPolicy: OnFailure
