apiVersion: v1
kind: ConfigMap #in production this would be a Secret, not a ConfigMap
metadata:
  name: go-weather-credentials
data:
  apiHost: weatherapi-com.p.rapidapi.com
  apiKey: api-key
  dsn: dsn-value
